In [2]:
import os 

In [3]:
os.environ["HF_TOKEN"] = "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"

In [4]:
## prepare data 
slide_dir = "PANDA_sample_tiles/054b6888604d963455bfff551518ece5/"
images =[os.path.join(slide_dir, img) for img in os.listdir(slide_dir) if img.endswith('.png')]
print(f"Found {len(images)} tiles")

Found 810 tiles


In [5]:
## download tile encoder through timm generation
import timm

tile_encoder = timm.create_model("hf_hub:prov-gigapath/prov-gigapath", pretrained=True)

config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████| 829/829 [00:00<00:00, 170kB/s]
pytorch_model.bin: 100%|███████████████████████████████████████████████████████████████████████████| 4.54G/4.54G [00:43<00:00, 104MB/s]


In [8]:
## check tile encoder
from torchsummary import summary
summary(tile_encoder)

Layer (type:depth-idx)                   Param #
├─PatchEmbed: 1-1                        --
|    └─Conv2d: 2-1                       1,181,184
|    └─Identity: 2-2                     --
├─Dropout: 1-2                           --
├─Identity: 1-3                          --
├─Identity: 1-4                          --
├─Sequential: 1-5                        --
|    └─Block: 2-3                        --
|    |    └─LayerNorm: 3-1               3,072
|    |    └─Attention: 3-2               9,443,328
|    |    └─LayerScale: 3-3              1,536
|    |    └─Identity: 3-4                --
|    |    └─LayerNorm: 3-5               3,072
|    |    └─GluMlp: 3-6                  18,884,096
|    |    └─LayerScale: 3-7              1,536
|    |    └─Identity: 3-8                --
|    └─Block: 2-4                        --
|    |    └─LayerNorm: 3-9               3,072
|    |    └─Attention: 3-10              9,443,328
|    |    └─LayerScale: 3-11             1,536
|    |    └─Identity: 3-

Layer (type:depth-idx)                   Param #
├─PatchEmbed: 1-1                        --
|    └─Conv2d: 2-1                       1,181,184
|    └─Identity: 2-2                     --
├─Dropout: 1-2                           --
├─Identity: 1-3                          --
├─Identity: 1-4                          --
├─Sequential: 1-5                        --
|    └─Block: 2-3                        --
|    |    └─LayerNorm: 3-1               3,072
|    |    └─Attention: 3-2               9,443,328
|    |    └─LayerScale: 3-3              1,536
|    |    └─Identity: 3-4                --
|    |    └─LayerNorm: 3-5               3,072
|    |    └─GluMlp: 3-6                  18,884,096
|    |    └─LayerScale: 3-7              1,536
|    |    └─Identity: 3-8                --
|    └─Block: 2-4                        --
|    |    └─LayerNorm: 3-9               3,072
|    |    └─Attention: 3-10              9,443,328
|    |    └─LayerScale: 3-11             1,536
|    |    └─Identity: 3-

In [9]:
## download slide encoder model 

import gigapath.slide_encoder as encoder

In [10]:
## THere are 3 models 
# 1. enc12l768d --> embed_dim = 768, depth = 12, mlp_ratio = 4. 
slide_encoder = encoder.create_model("hf_hub:prov-gigapath/prov-gigapath", "gigapath_slide_enc12l768d", 1536)

dilated_ratio:  [1, 2, 4, 8, 16]
segment_length:  [1024, 5792, 32768, 185363, 1048576]
Number of trainable LongNet parameters:  85148160
Global Pooling: False


slide_encoder.pth: 100%|█████████████████████████████████████████████████████████████████████████████| 345M/345M [00:03<00:00, 114MB/s]


 Successfully Loaded Pretrained GigaPath model from hf_hub:prov-gigapath/prov-gigapath 


In [12]:
## look at slide_encoder 
summary(slide_encoder)

Layer (type:depth-idx)                        Param #
├─PatchEmbed: 1-1                             --
|    └─Linear: 2-1                            1,180,416
|    └─Identity: 2-2                          --
├─LongNetEncoder: 1-2                         --
|    └─Dropout: 2-3                           --
|    └─ModuleList: 2-4                        --
|    |    └─LongNetEncoderLayer: 3-1          7,095,552
|    |    └─LongNetEncoderLayer: 3-2          7,095,552
|    |    └─LongNetEncoderLayer: 3-3          7,095,552
|    |    └─LongNetEncoderLayer: 3-4          7,095,552
|    |    └─LongNetEncoderLayer: 3-5          7,095,552
|    |    └─LongNetEncoderLayer: 3-6          7,095,552
|    |    └─LongNetEncoderLayer: 3-7          7,095,552
|    |    └─LongNetEncoderLayer: 3-8          7,095,552
|    |    └─LongNetEncoderLayer: 3-9          7,095,552
|    |    └─LongNetEncoderLayer: 3-10         7,095,552
|    |    └─LongNetEncoderLayer: 3-11         7,095,552
|    |    └─LongNetEncoderLay

Layer (type:depth-idx)                        Param #
├─PatchEmbed: 1-1                             --
|    └─Linear: 2-1                            1,180,416
|    └─Identity: 2-2                          --
├─LongNetEncoder: 1-2                         --
|    └─Dropout: 2-3                           --
|    └─ModuleList: 2-4                        --
|    |    └─LongNetEncoderLayer: 3-1          7,095,552
|    |    └─LongNetEncoderLayer: 3-2          7,095,552
|    |    └─LongNetEncoderLayer: 3-3          7,095,552
|    |    └─LongNetEncoderLayer: 3-4          7,095,552
|    |    └─LongNetEncoderLayer: 3-5          7,095,552
|    |    └─LongNetEncoderLayer: 3-6          7,095,552
|    |    └─LongNetEncoderLayer: 3-7          7,095,552
|    |    └─LongNetEncoderLayer: 3-8          7,095,552
|    |    └─LongNetEncoderLayer: 3-9          7,095,552
|    |    └─LongNetEncoderLayer: 3-10         7,095,552
|    |    └─LongNetEncoderLayer: 3-11         7,095,552
|    |    └─LongNetEncoderLay

In [14]:
## Encoding Part 

## tile encoding with image and store coord from preprocessing
from gigapath.pipeline import run_inference_with_tile_encoder

tile_encoder_outputs = run_inference_with_tile_encoder(images, tile_encoder) ## batch size = 128 


Running inference with tile encoder: 100%|███████████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.19s/it]


In [19]:
## return dic structure 
print(tile_encoder_outputs.keys())

dict_keys(['tile_embeds', 'coords'])


In [17]:
for k in tile_encoder_outputs.keys():
    print(f"tile_encoder_outputs[{k}].shape: {tile_encoder_outputs[k].shape}")

tile_encoder_outputs[tile_embeds].shape: torch.Size([810, 1536])
tile_encoder_outputs[coords].shape: torch.Size([810, 2])


In [27]:
print(tile_encoder_outputs['tile_embeds'].shape == 2)

False


In [24]:
print(tile_encoder_outputs['tile_embeds'][0])
print(tile_encoder_outputs['coords'][0])

tensor([-0.8817, -0.9265, -0.7653,  ..., -0.3008, -0.4806, -0.5998])
tensor([ 6040., 26952.])


In [ ]:
## slide encoding with position 

In [28]:
from gigapath.pipeline import run_inference_with_slide_encoder

In [29]:
slide_embeds = run_inference_with_slide_encoder(slide_encoder_model=slide_encoder, **tile_encoder_outputs)

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 12/12 [00:00<00:00, 13.69it/s]


In [30]:
print(slide_embeds.keys())

dict_keys(['layer_0_embed', 'layer_1_embed', 'layer_2_embed', 'layer_3_embed', 'layer_4_embed', 'layer_5_embed', 'layer_6_embed', 'layer_7_embed', 'layer_8_embed', 'layer_9_embed', 'layer_10_embed', 'layer_11_embed', 'layer_12_embed', 'last_layer_embed'])


In [32]:
for i in slide_embeds.keys():
    print(f"{i} .Shape=> {slide_embeds[i].shape}")

layer_0_embed .Shape=> torch.Size([1, 768])
layer_1_embed .Shape=> torch.Size([1, 768])
layer_2_embed .Shape=> torch.Size([1, 768])
layer_3_embed .Shape=> torch.Size([1, 768])
layer_4_embed .Shape=> torch.Size([1, 768])
layer_5_embed .Shape=> torch.Size([1, 768])
layer_6_embed .Shape=> torch.Size([1, 768])
layer_7_embed .Shape=> torch.Size([1, 768])
layer_8_embed .Shape=> torch.Size([1, 768])
layer_9_embed .Shape=> torch.Size([1, 768])
layer_10_embed .Shape=> torch.Size([1, 768])
layer_11_embed .Shape=> torch.Size([1, 768])
layer_12_embed .Shape=> torch.Size([1, 768])
last_layer_embed .Shape=> torch.Size([1, 768])


In [34]:
## check layer 1 and layer 12 
print(slide_embeds['layer_0_embed'])
print('-------------')
print(slide_embeds['last_layer_embed'])

tensor([[-4.5210e-01,  1.7855e+00,  2.5990e-01, -9.2623e-02, -7.9379e-02,
         -4.9030e-01,  5.2150e-01,  2.0427e-02, -8.7831e-01, -1.0923e+00,
          9.1779e-01,  1.9031e+00, -1.8882e-01,  4.0819e+00, -9.9635e-01,
          6.6815e-01,  9.3187e-01,  4.6784e-01,  6.5349e-01,  4.8378e-01,
         -8.1687e-02,  5.9407e-02,  3.2209e+00, -3.5371e-01, -1.0952e+00,
          7.4126e-01, -1.5051e-01, -1.1173e+00, -3.1420e-01, -8.2539e-01,
         -4.4671e-02,  3.6703e-01,  1.6183e-01,  1.8128e-01,  1.3408e-01,
          1.5553e+00, -2.4995e+00, -3.0818e-01,  3.6680e-01,  7.0053e-01,
         -2.4750e-01, -2.1626e-01, -4.1587e-01, -4.6226e-01, -2.6574e-01,
          3.5805e-01,  1.5961e-01,  2.3117e-01, -1.8021e-01, -1.3967e-02,
         -2.4106e-01, -5.3606e-01, -2.0481e-01, -4.8502e-01, -1.9846e-01,
          2.6415e-01,  6.1616e-02, -1.9794e-01,  1.9629e-01,  2.4304e-02,
         -1.2413e-02,  1.7330e-01,  2.2374e-01,  1.9147e-02, -6.4836e-01,
          2.2571e-01,  2.3290e-02,  4.

In [40]:
## move gpu to cpu 
cpu= {}
for i in slide_embeds.keys():
    cpu[i] = slide_embeds[i].cpu()




In [41]:
print(cpu['layer_0_embed'])

tensor([[-4.5210e-01,  1.7855e+00,  2.5990e-01, -9.2623e-02, -7.9379e-02,
         -4.9030e-01,  5.2150e-01,  2.0427e-02, -8.7831e-01, -1.0923e+00,
          9.1779e-01,  1.9031e+00, -1.8882e-01,  4.0819e+00, -9.9635e-01,
          6.6815e-01,  9.3187e-01,  4.6784e-01,  6.5349e-01,  4.8378e-01,
         -8.1687e-02,  5.9407e-02,  3.2209e+00, -3.5371e-01, -1.0952e+00,
          7.4126e-01, -1.5051e-01, -1.1173e+00, -3.1420e-01, -8.2539e-01,
         -4.4671e-02,  3.6703e-01,  1.6183e-01,  1.8128e-01,  1.3408e-01,
          1.5553e+00, -2.4995e+00, -3.0818e-01,  3.6680e-01,  7.0053e-01,
         -2.4750e-01, -2.1626e-01, -4.1587e-01, -4.6226e-01, -2.6574e-01,
          3.5805e-01,  1.5961e-01,  2.3117e-01, -1.8021e-01, -1.3967e-02,
         -2.4106e-01, -5.3606e-01, -2.0481e-01, -4.8502e-01, -1.9846e-01,
          2.6415e-01,  6.1616e-02, -1.9794e-01,  1.9629e-01,  2.4304e-02,
         -1.2413e-02,  1.7330e-01,  2.2374e-01,  1.9147e-02, -6.4836e-01,
          2.2571e-01,  2.3290e-02,  4.